version: '3'

#TODO add reverse proxy 
#TODO add secrets
#TODO separate netwqorks

services:
  redis_server:
    image: redis:alpine
    command: redis-server --requirepass password
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

# change image baesd on dockerhub
  app:
    image: smatko/node-express-redis-socketio-docker-starter
    ports:
      - "80:5000"
    volumes:
      - .:/opt/app/
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=app-database
      - REDIS_HOST=redis_server
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - JWT_SECRET=secret
      - PORT=5000
    depends_on:
      - db
      - redis_server
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=app-database
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/app-database --quiet` ] && echo 0 || echo 1"
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
    volumes:
      - mongodb-data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
    mongodb-data:

